version: '3'

services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - logging_net
    restart: unless-stopped
    environment:
      - LOKI_RETENTION_ENABLED=true
      - LOKI_RETENTION_PERIOD=72h

  log_server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "6008:6008"
    networks:
      - logging_net
    restart: unless-stopped

volumes:
  loki_data:

networks:
  logging_net:
    driver: bridge
